### ISSUE TITLE
Origin Response Type should include optional body

### ISSUE THREAD

**Issue by ispyinternet** [jill64/types-lambda#155]
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-updating-http-responses.html#:~:text=When%20you're%20working%20with,the%20value%20to%20be%20empty.

**Comment by jill64** [comment]
Thank you for opening this issue!
Hmmm, you mention this part of the document, right?

> You can also replace the HTTP responses in viewer and origin request events. For more information, see Generate HTTP responses in request triggers. When you're working with the HTTP response, Lambda@Edge does not expose the body that is returned by the origin server to the origin-response trigger. You can generate a static content body by setting it to the desired value, or remove the body inside the function by setting the value to be empty. If you don't update the body field in your function, the original body returned by the origin server is returned back to viewer.

And as stated here, when using HTTP responses, Lambda@Edge does not expose the body returned from the origin server to the origin-response trigger.

> Lambda@Edge does not expose the body that is returned by the origin server to the origin-response trigger.

Also, reference to another document shows that the OriginResponse object does not contain a body property.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html#response-event-fields-response

This indicates that Lambda@Edge cannot directly reference the body of origin.

If the response body from the origin is changed, this can be done by generating a value in the function callback or return value, or by setting it to empty.

Therefore, there should be no problem with the type declarations in this library.
If I am wrong about anything, please let me know.

**Comment by ispyinternet** [comment]
This part of the doc states that you can return a body if you choose.

> You can generate a static content body by setting it to the desired value, or remove the body inside the function by setting the value to be empty. If you don't update the body field in your function, the original body returned by the origin server is returned back to viewer.

 Indeed I am using an origin response lambda to return the sveltekit SPA fallback html if the requested file is not found in S3.

**Comment by jill64** [comment]
I see.
I understand.

You are probably referring to the callback or return value of the handler.

This handler type controls whether the body property is included or not, depending on the type argument.

By default, the body property is not included, but setting it to `OriginResponseHandler<‘s3’,’include-body’>` makes the body property available.

Therefore, the following handler type definition should solve the problem.

```ts
const handler: OriginResponseHandler<'s3', 'include-body'> = async () => {
  return {
    status: 200,
    headers: {
      'content-type': 'text/plain'
    },
    body: 'Hello, World!'
  }
}

// or

const handler: OriginResponseHandler<'s3', 'include-body'> = async (
  event,
  context,
  callback
) => {
  callback(null, {
    status: '200',
    headers: {
      'content-type': [
        {
          key: 'Content-Type',
          value: 'text/plain'
        }
      ]
    },
    body: 'Hello, World!'
  })
}


```

P.S.
I'm not good at English, so I use Google Translate.
Sorry if there are any mistakes in the context.

**Comment by jill64** [comment]
understood.
This is a deliberately designed constraint.
This is because the presence of `response.body` may cause users to mistakenly think that they can read and work with `response.body` from origin.
But you can't actually read the `body` from origin, and all you can do with Lambda@Edge is override the return value with a static value.
So instead of rewriting the value of `response`, we need to create a new object.
(as per the workaround shown above)
